package com.xie.smfs;

import com.xie.smfs.api.ConfigAPI;
import com.xie.smfs.api.GhostAPI;
import com.xie.smfs.api.TameableItemAPI;
import com.xie.smfs.api.impl.ConfigAPIImpl;
import com.xie.smfs.api.impl.GhostAPIImpl;
import com.xie.smfs.api.impl.TameableItemAPIImpl;
import com.xie.smfs.command.EasterEggCommand;
import com.xie.smfs.command.GuiNiaoCommand;
import com.xie.smfs.command.XianWangCommand;
import com.xie.smfs.command.XieCommand;
import com.xie.smfs.common.events.PlayerEvents;
import com.xie.smfs.effect.SpiritAttributes;
import com.xie.smfs.entity.GhostEntity;
import com.xie.smfs.entity.ghost.BlockGhostEntity;
import com.xie.smfs.entity.ghost.BoxGhostEntity;
import com.xie.smfs.entity.ghost.DeathSightGhostEntity;
import com.xie.smfs.entity.ghost.FogGhostEntity;
import com.xie.smfs.entity.ghost.GanshiBrideGhostEntity;
import com.xie.smfs.entity.ghost.GhostDreamEntity;
import com.xie.smfs.entity.ghost.GhostPressureEntity;
import com.xie.smfs.entity.ghost.GhostShadowHeadEntity;
import com.xie.smfs.entity.ghost.GhostWindEntity;
import com.xie.smfs.entity.ghost.GiantMaleCorpseGhostEntity;
import com.xie.smfs.entity.ghost.GiantShadowGhostEntity;
import com.xie.smfs.entity.ghost.JumpGhostEntity;
import com.xie.smfs.entity.ghost.LostGhostEntity;
import com.xie.smfs.entity.ghost.LuoQianGhostEntity;
import com.xie.smfs.entity.ghost.UntouchableGhostEntity;
import com.xie.smfs.entity.ghost.VillagerGhostEntity;
import com.xie.smfs.entity.master.GuiNiaoEntity;
import com.xie.smfs.entity.master.LiJunEntity;
import com.xie.smfs.entity.master.LiLePingEntity;
import com.xie.smfs.entity.master.NPC1Entity;
import com.xie.smfs.entity.master.NPC2Entity;
import com.xie.smfs.entity.master.NPC3Entity;
import com.xie.smfs.entity.master.NPC4Entity;
import com.xie.smfs.entity.master.NPC5Entity;
import com.xie.smfs.entity.master.NPC6Entity;
import com.xie.smfs.entity.master.XianWangEntity;
import com.xie.smfs.entity.master.YanLiEntity;
import com.xie.smfs.entity.master.YangJianEntity;
import com.xie.smfs.entity.master.YangXiaoEntity;
import com.xie.smfs.entity.master.YinQiEntity;
import com.xie.smfs.entity.master.ZhaoKaiMingEntity;
import com.xie.smfs.entity.other.CaoYanHuaEntity;
import com.xie.smfs.entity.other.ChenDoctorEntity;
import com.xie.smfs.entity.other.GhostSlaveEntity;
import com.xie.smfs.entity.other.LiuXiaoYuEntity;
import com.xie.smfs.entity.other.PlayerGhostEntity;
import com.xie.smfs.entity.other.WangXiaoMingEntity;
import com.xie.smfs.event.EntityAttackListener;
import com.xie.smfs.event.FootprintGeneratorEventHandler;
import com.xie.smfs.event.GhostDeathHandler;
import com.xie.smfs.event.GhostInteractionHandler;
import com.xie.smfs.event.GhostMasterTalkHandler;
import com.xie.smfs.event.GhostspawnsHandler;
import com.xie.smfs.event.GoldenContainerPortalHandler;
import com.xie.smfs.event.ModEvents;
import com.xie.smfs.event.ModLootTableEvents;
import com.xie.smfs.event.PlayerDeathHandler;
import com.xie.smfs.event.PlayerJoinListener;
import com.xie.smfs.event.PlayerReviveHandler;
import com.xie.smfs.event.QuestEventHandler;
import com.xie.smfs.event.RecipeUnlockEventHandler;
import com.xie.smfs.event.SeedDropEventHandler;
import com.xie.smfs.event.ServerTickHandler;
import com.xie.smfs.event.SilentGhostChatHandler;
import com.xie.smfs.event.SilentGhostTeleportHandler;
import com.xie.smfs.event.WeaponOilEventHandler;
import com.xie.smfs.event.YangJianChatHandler;
import com.xie.smfs.event.network.GhostPressureDetectionHandler;
import com.xie.smfs.manager.GhostLimitManager;
import com.xie.smfs.manager.GhostSpawnManager;
import com.xie.smfs.manager.RecipeUnlockManager;
import com.xie.smfs.network.ModNetwork;
import com.xie.smfs.network.core.SpiritNetworkHandler;
import com.xie.smfs.recipe.GhostFurnaceRecipeType;
import com.xie.smfs.registry.ModBlockEntities;
import com.xie.smfs.registry.ModBlocks;
import com.xie.smfs.registry.ModEffects;
import com.xie.smfs.registry.ModEntities;
import com.xie.smfs.registry.ModFluids;
import com.xie.smfs.registry.ModItems;
import com.xie.smfs.registry.ModScreenHandlers;
import com.xie.smfs.registry.ModSounds;
import com.xie.smfs.registry.ModStructureType;
import com.xie.smfs.util.PlayerBlockActionTracker;
import com.xie.smfs.worldgen.ModStructureProcessors;
import com.xie.smfs.worldgen.ModWorldGen;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.player.UseBlockCallback;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.Identifier;
import net.minecraft.world.World;
import net.minecraft.world.dimension.DimensionType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Smfs implements ModInitializer {
   public static final String MOD_ID = "smfs";
   public static final Logger LOGGER = LoggerFactory.getLogger("smfs");
   public static final Identifier SECOND_INVENTORY_ID = new Identifier("smfs", "second_inventory");
   public static final Identifier OPEN_GHOST_SCREEN_PACKET = new Identifier("smfs", "open_ghost_screen");
   public static final RegistryKey<World> SPIRIT_REALM_DIMENSION = RegistryKey.method_29179(RegistryKeys.field_41223, new Identifier("smfs", "spirit_realm"));
   public static final RegistryKey<DimensionType> SPIRIT_REALM_DIMENSION_TYPE = RegistryKey.method_29179(
      RegistryKeys.field_41241, new Identifier("smfs", "spirit_realm")
   );
   public static final RegistryKey<World> GHOST_DREAM_DIMENSION = RegistryKey.method_29179(RegistryKeys.field_41223, new Identifier("smfs", "ghost_dream"));
   public static final RegistryKey<DimensionType> GHOST_DREAM_DIMENSION_TYPE = RegistryKey.method_29179(
      RegistryKeys.field_41241, new Identifier("smfs", "ghost_dream")
   );

   @Override
   public void onInitialize() {
      LOGGER.info("=================开始初始化神秘复苏模组=================");
      PlayerBlockActionTracker.registerEvents();
      ModStructureProcessors.register();
      ModWorldGen.register();
      this.registerGhostAttributes();
      ModEffects.registerEffects();
      SpiritAttributes.register();
      ModStructureType.registerStructureTypes();
      ModBlocks.registerBlocks();
      ModBlockEntities.registerBlockEntities();
      ModItems.registerItems();
      ModFluids.registerFluids();
      ModLootTableEvents.register();
      ModSounds.registerSounds();
      ModEvents.registerEvents();
      PlayerEvents.register();
      PlayerDeathHandler.register();
      PlayerReviveHandler.register();
      GhostDeathHandler.register();
      GhostLimitManager.register();
      ServerTickHandler.register();
      GhostPressureDetectionHandler.register();
      GhostspawnsHandler.register();
      EntityAttackListener.register();
      PlayerJoinListener.register();
      FootprintGeneratorEventHandler.register();
      SeedDropEventHandler.register();
      SpiritNetworkHandler.registerReceivers();
      ModNetwork.register();
      ServerLifecycleEvents.SERVER_STARTED.register(this::onServerStarted);
      UseEntityCallback.EVENT.register(new GhostInteractionHandler());
      UseEntityCallback.EVENT.register(new GhostMasterTalkHandler());
      UseBlockCallback.EVENT.register(new GoldenContainerPortalHandler());
      ModScreenHandlers.registerScreenHandlers();
      CommandRegistrationCallback.EVENT.register(XieCommand::register);
      CommandRegistrationCallback.EVENT.register(EasterEggCommand::register);
      CommandRegistrationCallback.EVENT.register(XianWangCommand::register);
      CommandRegistrationCallback.EVENT.register(GuiNiaoCommand::register);
      QuestEventHandler.register();
      WeaponOilEventHandler.register();
      BoxGhostEntity.registerChestInteractionListener();
      GhostFurnaceRecipeType.register();
      RecipeUnlockManager.initializeDefaultConditions();
      RecipeUnlockEventHandler.register();
      YangJianChatHandler.register();
      SilentGhostChatHandler.register();
      SilentGhostTeleportHandler.register();
      GhostAPI.register(new GhostAPIImpl());
      TameableItemAPI.register(new TameableItemAPIImpl());
      ConfigAPI.register(new ConfigAPIImpl());
      LOGGER.info("=================神秘复苏模组初始化完成=================");
   }

   private void onServerStarted(MinecraftServer server) {
      if (server.method_30002() != null) {
         GhostSpawnManager.loadLockedGhostTypes(server.method_30002());
      }
   }

   private void registerGhostAttributes() {
      FabricDefaultAttributeRegistry.register(ModEntities.FOOD_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.TAITOU_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.DITOU_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.QIAOMEN_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_MERCHANT, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.BOX_GHOST, BoxGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.VILLAGER_GHOST, VillagerGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.JUMP_GHOST, JumpGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.FOG_GHOST, FogGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.UNTOUCHABLE_GHOST, UntouchableGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.DEATH_SIGHT_GHOST, DeathSightGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.BLOCK_GHOST, BlockGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.LOST_GHOST, LostGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_WIND, GhostWindEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_PRESSURE, GhostPressureEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.PLAYER_GHOST, PlayerGhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_SLAVE, GhostSlaveEntity.createGhostSlaveAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GIANT_SHADOW_GHOST, GiantShadowGhostEntity.createAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GANSHI_BRIDE_GHOST, GanshiBrideGhostEntity.createAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GIANT_MALE_CORPSE_GHOST, GiantMaleCorpseGhostEntity.createLivingAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CROP_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.STEP_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.TRASH_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.WATER_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.BURN_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CRYING_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.SUONA_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GONG_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.SILENT_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GOODS_SELLER_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_OFFICER, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.PLAGUE_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.MINERAL_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.SHADOW_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_SHADOW_HEAD, GhostShadowHeadEntity.createLivingAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.DOOR_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_SMOKE, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_CHILD, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.SNEAK_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CLOTHES_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.PUPPET_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GRAVE_EARTH_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.WANG_XIAO_MING, WangXiaoMingEntity.createWangXiaoMingAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CHEN_DOCTOR, ChenDoctorEntity.createChenDoctorAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CAO_YAN_HUA, CaoYanHuaEntity.createCaoYanHuaAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.LIU_XIAO_YU, LiuXiaoYuEntity.createLiuXiaoYuAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.YANG_JIAN, YangJianEntity.createYangJianAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.LI_JUN, LiJunEntity.createLiJunAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.CAO_YANG, LiJunEntity.createLiJunAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.YE_ZHEN, LiJunEntity.createLiJunAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.FANG_SHI_MIN, LiJunEntity.createLiJunAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.FENG_QUAN, LiJunEntity.createLiJunAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC1, NPC1Entity.createNPC1Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC2, NPC2Entity.createNPC2Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC3, NPC3Entity.createNPC3Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC4, NPC4Entity.createNPC4Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC5, NPC5Entity.createNPC5Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.NPC6, NPC6Entity.createNPC6Attributes());
      FabricDefaultAttributeRegistry.register(ModEntities.YAN_LI, YanLiEntity.createYanLiAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.LI_LE_PING, LiLePingEntity.createLiLePingAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.ZHAO_KAI_MING, ZhaoKaiMingEntity.createZhaoKaiMingAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.YANG_XIAO, YangXiaoEntity.createYangXiaoAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GHOST_DREAM, GhostDreamEntity.createGhostDreamAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.XINKAI_GHOST, GhostEntity.createGhostAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.YIN_QI, YinQiEntity.createYinQiAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.XIAN_WANG, XianWangEntity.createXianWangAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.GUI_NIAO, GuiNiaoEntity.createGuiNiaoAttributes());
      FabricDefaultAttributeRegistry.register(ModEntities.LUO_QIAN_GHOST, LuoQianGhostEntity.createLivingAttributes());
   }
}
