package com.xie.smfs.registry;

import com.xie.smfs.effect.BlackGhostDomainEffect;
import com.xie.smfs.effect.BlackGhostDomainTargetEffect;
import com.xie.smfs.effect.BlueGhostDomainEffect;
import com.xie.smfs.effect.CyanGhostDomainEffect;
import com.xie.smfs.effect.DeafnessEffect;
import com.xie.smfs.effect.DreamEffect;
import com.xie.smfs.effect.FatalPoisonEffect;
import com.xie.smfs.effect.GhostDeadlockEffect;
import com.xie.smfs.effect.GhostKnockEffect;
import com.xie.smfs.effect.GhostPressureEffect;
import com.xie.smfs.effect.GhostSuppressionEffect;
import com.xie.smfs.effect.GhostWindEffect;
import com.xie.smfs.effect.GoldenGhostDomainEffect;
import com.xie.smfs.effect.GrayGhostDomainEffect;
import com.xie.smfs.effect.GreenGhostDomainEffect;
import com.xie.smfs.effect.IllusionCurseEffect;
import com.xie.smfs.effect.KnockingCurseEffect;
import com.xie.smfs.effect.LostStatusEffect;
import com.xie.smfs.effect.MarkCurseEffect;
import com.xie.smfs.effect.MusicBoxCurseEffect;
import com.xie.smfs.effect.PlagueEffect;
import com.xie.smfs.effect.PurificationEffect;
import com.xie.smfs.effect.PurpleGhostDomainEffect;
import com.xie.smfs.effect.PurpleGhostDomainVisualEffect;
import com.xie.smfs.effect.RedGhostDomainEffect;
import com.xie.smfs.effect.RevivalSuppressionEffect;
import com.xie.smfs.effect.ScapegoatMarkEffect;
import com.xie.smfs.effect.SilenceEffect;
import com.xie.smfs.effect.SpiritErosionEffect;
import com.xie.smfs.effect.SpiritImmunityEffect;
import com.xie.smfs.effect.SpiritSurgeStatusEffect;
import com.xie.smfs.effect.StarvingGhostCurseEffect;
import com.xie.smfs.effect.ThickFogEffect;
import com.xie.smfs.effect.TraumaCurseEffect;
import com.xie.smfs.effect.WishCurseEffect;
import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModEffects {
   public static final StatusEffect GHOST_WIND_EFFECT = new GhostWindEffect();
   public static final StatusEffect KNOCKING_CURSE = new KnockingCurseEffect();
   public static final StatusEffect GHOST_KNOCK = new GhostKnockEffect();
   public static final StatusEffect LOST = new LostStatusEffect();
   public static final StatusEffect STARVING_GHOST_CURSE = new StarvingGhostCurseEffect();
   public static final StatusEffect SPIRIT_SURGE = new SpiritSurgeStatusEffect();
   public static final StatusEffect RED_GHOST_DOMAIN = new RedGhostDomainEffect();
   public static final StatusEffect RED_GHOST_DOMAIN_TARGET = new RedGhostDomainEffect();
   public static final StatusEffect THICK_FOG = new ThickFogEffect();
   public static final StatusEffect THICK_FOG_TARGET = new ThickFogEffect();
   public static final StatusEffect FATAL_POISON = new FatalPoisonEffect();
   public static final StatusEffect TRAUMA_CURSE = new TraumaCurseEffect();
   public static final StatusEffect ILLUSION_CURSE = new IllusionCurseEffect();
   public static final StatusEffect SILENCE = new SilenceEffect();
   public static final StatusEffect GREEN_GHOST_DOMAIN = new GreenGhostDomainEffect();
   public static final StatusEffect GREEN_GHOST_DOMAIN_TARGET = new GreenGhostDomainEffect();
   public static final StatusEffect BLUE_GHOST_DOMAIN = new BlueGhostDomainEffect();
   public static final StatusEffect BLUE_GHOST_DOMAIN_TARGET = new BlueGhostDomainEffect();
   public static final StatusEffect GRAY_GHOST_DOMAIN = new GrayGhostDomainEffect();
   public static final StatusEffect GRAY_GHOST_DOMAIN_TARGET = new GrayGhostDomainEffect();
   public static final StatusEffect GOLDEN_GHOST_DOMAIN = new GoldenGhostDomainEffect();
   public static final StatusEffect GOLDEN_GHOST_DOMAIN_TARGET = new GoldenGhostDomainEffect();
   public static final StatusEffect PURPLE_GHOST_DOMAIN = new PurpleGhostDomainEffect();
   public static final StatusEffect PURPLE_GHOST_DOMAIN_TARGET = new PurpleGhostDomainEffect();
   public static final StatusEffect PURPLE_GHOST_DOMAIN_VISUAL = new PurpleGhostDomainVisualEffect();
   public static final StatusEffect BLACK_GHOST_DOMAIN = new BlackGhostDomainEffect();
   public static final StatusEffect BLACK_GHOST_DOMAIN_TARGET = new BlackGhostDomainTargetEffect();
   public static final StatusEffect CYAN_GHOST_DOMAIN = new CyanGhostDomainEffect();
   public static final StatusEffect CYAN_GHOST_DOMAIN_TARGET = new CyanGhostDomainEffect();
   public static final StatusEffect MARK_CURSE = new MarkCurseEffect();
   public static final StatusEffect GHOST_SUPPRESSION = new GhostSuppressionEffect();
   public static final StatusEffect GHOST_PRESSURE = new GhostPressureEffect();
   public static final StatusEffect SCAPEGOAT_MARK = new ScapegoatMarkEffect();
   public static final StatusEffect SPIRIT_IMMUNITY = new SpiritImmunityEffect();
   public static final StatusEffect SPIRIT_EROSION = new SpiritErosionEffect();
   public static final StatusEffect PLAGUE = new PlagueEffect();
   public static final StatusEffect WISH_CURSE = new WishCurseEffect();
   public static final StatusEffect DEAFNESS = new DeafnessEffect();
   public static final StatusEffect PURIFICATION = new PurificationEffect();
   public static final StatusEffect DREAM = new DreamEffect();
   public static final StatusEffect MUSIC_BOX_CURSE = new MusicBoxCurseEffect();
   public static final StatusEffect GHOST_DEADLOCK = new GhostDeadlockEffect();
   public static final StatusEffect REVIVAL_SUPPRESSION = new RevivalSuppressionEffect();

   public static void registerEffects() {
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "knocking_curse"), KNOCKING_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "ghost_knock"), GHOST_KNOCK);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "lost"), LOST);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "starving_ghost_curse"), STARVING_GHOST_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "spirit_surge"), SPIRIT_SURGE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "red_ghost_domain"), RED_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "red_ghost_domain_target"), RED_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "thick_fog"), THICK_FOG);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "thick_fog_target"), THICK_FOG_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "fatal_poison"), FATAL_POISON);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "trauma_curse"), TRAUMA_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "illusion_curse"), ILLUSION_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "silence"), SILENCE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "green_ghost_domain"), GREEN_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "green_ghost_domain_target"), GREEN_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "blue_ghost_domain"), BLUE_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "blue_ghost_domain_target"), BLUE_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "gray_ghost_domain"), GRAY_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "gray_ghost_domain_target"), GRAY_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "golden_ghost_domain"), GOLDEN_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "golden_ghost_domain_target"), GOLDEN_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "purple_ghost_domain"), PURPLE_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "purple_ghost_domain_target"), PURPLE_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "purple_ghost_domain_visual"), PURPLE_GHOST_DOMAIN_VISUAL);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "black_ghost_domain"), BLACK_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "black_ghost_domain_target"), BLACK_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "cyan_ghost_domain"), CYAN_GHOST_DOMAIN);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "cyan_ghost_domain_target"), CYAN_GHOST_DOMAIN_TARGET);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "mark_curse"), MARK_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "ghost_suppression"), GHOST_SUPPRESSION);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "ghost_pressure"), GHOST_PRESSURE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "ghost_wind_effect"), GHOST_WIND_EFFECT);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "scapegoat_mark"), SCAPEGOAT_MARK);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "spirit_immunity"), SPIRIT_IMMUNITY);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "spirit_erosion"), SPIRIT_EROSION);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "plague"), PLAGUE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "wish_curse"), WISH_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "deafness"), DEAFNESS);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "purification"), PURIFICATION);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "dream"), DREAM);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "music_box_curse"), MUSIC_BOX_CURSE);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "ghost_deadlock"), GHOST_DEADLOCK);
      Registry.register(Registries.STATUS_EFFECT, new Identifier("smfs", "revival_suppression"), REVIVAL_SUPPRESSION);
   }
}
