package com.xie.smfs.network.core;

import com.xie.smfs.common.events.PlayerEvents;
import com.xie.smfs.network.packets.skills.c2s.ClientBlockGhostVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientBoxGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientCandyGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientConsumeShardC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientCryingGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientDeathSightGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientDitouGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientDoorGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientFoodGhostVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientFuneralMusicGhostGSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientFuneralMusicGhostNSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientFuneralMusicGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientFuneralMusicGhostVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGanshiBrideGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostBloodSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostDomainMoveEntityC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostDomainPauseTimeC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostDomainRemoveBuffsC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostDomainTeleportC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostDomainToggleC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostEyeJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostMerchantSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostOfficerGSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostOfficerRestartC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostOfficerSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostOfficerVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostPressureSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostShadowHeadGSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostShadowHeadJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostShadowHeadNSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostShadowHeadUnbindControlC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostShadowHeadVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGhostWindSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGiantShadowGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientGongGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientJumpGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientLostGhostBlindC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientLostGhostRestartC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientLostGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientLostGhostSlowC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientMineralGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientPlagueGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientQiaomenGhostGSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientQiaomenGhostNSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientQiaomenGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientQiaomenGhostVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientScapegoatGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientShadowGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientSilentGhostJSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientSuonaGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientSwitchMainGhostC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientSwitchMainGhostToSlotC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientTaitouGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientVillagerGhostGSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientVillagerGhostNSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientVillagerGhostSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.ClientVillagerGhostVSkillC2SPacket;
import com.xie.smfs.network.packets.skills.c2s.GhostDomainLevelC2SPacket;
import com.xie.smfs.network.packets.ui.c2s.GhostDeadlockSelectC2SPacket;
import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.network.PacketByteBuf;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SpiritNetworkHandler {
   private static final Logger LOGGER = LoggerFactory.getLogger("smfs/SpiritNetworkHandler");
   public static final Identifier SYNC_SPIRIT_DATA = new Identifier("smfs", "sync_spirit_data");

   public static void registerReceivers() {
      LOGGER.info("注册网络数据包接收器");
      ClientGhostDomainToggleC2SPacket.register();
      ClientGhostDomainTeleportC2SPacket.register();
      ClientGhostDomainMoveEntityC2SPacket.register();
      ClientGhostDomainPauseTimeC2SPacket.register();
      ClientGhostDomainRemoveBuffsC2SPacket.register();
      GhostDomainLevelC2SPacket.register();
      ClientTaitouGhostSkillC2SPacket.register();
      ClientDitouGhostSkillC2SPacket.register();
      ClientBoxGhostSkillC2SPacket.register();
      ClientBlockGhostVSkillC2SPacket.register();
      ClientDeathSightGhostSkillC2SPacket.register();
      ClientGhostMerchantSkillC2SPacket.register();
      ClientJumpGhostSkillC2SPacket.register();
      ClientVillagerGhostSkillC2SPacket.register();
      ClientVillagerGhostNSkillC2SPacket.register();
      ClientVillagerGhostGSkillC2SPacket.register();
      ClientVillagerGhostVSkillC2SPacket.register();
      ClientLostGhostSkillC2SPacket.register();
      ClientLostGhostBlindC2SPacket.register();
      ClientLostGhostSlowC2SPacket.register();
      ClientLostGhostRestartC2SPacket.register();
      ClientGhostOfficerRestartC2SPacket.register();
      ClientGhostOfficerSkillC2SPacket.register();
      ClientGhostOfficerGSkillC2SPacket.register();
      ClientGhostOfficerVSkillC2SPacket.register();
      ClientQiaomenGhostSkillC2SPacket.register();
      ClientQiaomenGhostNSkillC2SPacket.register();
      ClientQiaomenGhostGSkillC2SPacket.register();
      ClientQiaomenGhostVSkillC2SPacket.register();
      ClientFoodGhostVSkillC2SPacket.register();
      ClientGiantShadowGhostSkillC2SPacket.register();
      ClientGanshiBrideGhostSkillC2SPacket.register();
      ClientCryingGhostSkillC2SPacket.register();
      ClientSuonaGhostSkillC2SPacket.register();
      ClientGongGhostSkillC2SPacket.register();
      ClientGhostPressureSkillC2SPacket.register();
      ClientGhostWindSkillC2SPacket.register();
      ClientConsumeShardC2SPacket.register();
      ClientGhostBloodSkillC2SPacket.register();
      ClientCandyGhostJSkillC2SPacket.register();
      ClientGhostEyeJSkillC2SPacket.register();
      ClientSilentGhostJSkillC2SPacket.register();
      ClientSwitchMainGhostC2SPacket.register();
      ClientSwitchMainGhostToSlotC2SPacket.register();
      ClientScapegoatGhostSkillC2SPacket.register();
      ClientPlagueGhostJSkillC2SPacket.register();
      ClientMineralGhostJSkillC2SPacket.register();
      ClientShadowGhostJSkillC2SPacket.register();
      ClientDoorGhostJSkillC2SPacket.register();
      ClientGhostShadowHeadJSkillC2SPacket.register();
      ClientGhostShadowHeadVSkillC2SPacket.register();
      ClientGhostShadowHeadGSkillC2SPacket.register();
      ClientGhostShadowHeadNSkillC2SPacket.register();
      ClientGhostShadowHeadUnbindControlC2SPacket.register();
      ClientFuneralMusicGhostSkillC2SPacket.register();
      ClientFuneralMusicGhostNSkillC2SPacket.register();
      ClientFuneralMusicGhostGSkillC2SPacket.register();
      ClientFuneralMusicGhostVSkillC2SPacket.register();
      GhostDeadlockSelectC2SPacket.register();
      LOGGER.info("鬼域数据包接收器注册完成");
   }

   public static void syncSpiritData(ServerPlayerEntity player) {
      NbtCompound spiritData = PlayerEvents.getSpiritAttributes(player);
      PacketByteBuf buf = PacketByteBufs.create();
      buf.method_10794(spiritData);
      ServerPlayNetworking.send(player, SYNC_SPIRIT_DATA, buf);
   }
}
